### ISSUE TITLE
🚪 Property: initialize

### ISSUE THREAD

**Issue by Guthen** [VR-GMod/VirtualRoleplay#3]
Create an owning system for doors and vehicles :

### Bases
- [x] Buy/Sell property
- [x] Allow/Disallow ownership
- [x] Unlock/Lock property
- [x] Create a copy of key
- [x] Delete key
- [x] Drop key
- [x] Rename key
- [x] Keys inventory

**Comment by Nogitsu** [comment]
- [ ] Change the "Sell door for $X" button to a "Change keylock for $X"
- [ ] Add the possibility to sell keys (50% of the copy price ?)
- [ ] When selling a key, if it's the last one of the door, make the door buyable
